In [2]:
#task 3
#Even when it seems as the shortest part of this lab, it took a lot of time to understand, how to launch pipeline
#!pip install ipywidgets
#!pip install transformers
#!pip3 install PyJWT
#!pip install 'h5py==2.10.0' --force-reinstall
!jupyter nbextension enable --py widgetsnbextension
#!pip install tensorflow
#!pip install google-colab
import codecs
from transformers import pipeline
from ipywidgets import FloatProgress
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
#from google.colab import files

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK


In [3]:
classifier = pipeline('sentiment-analysis')

All model checkpoint weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [4]:
text_one = 'Give me A please'
classifier(text_one)

[{'label': 'POSITIVE', 'score': 0.9996846318244934}]

In [5]:
text_two = 'Or Give me B please :)'
classifier(text_two)

[{'label': 'POSITIVE', 'score': 0.9926418662071228}]

In [6]:
text_three = 'I am Oleksii Chalyi'
classifier(text_three)

[{'label': 'POSITIVE', 'score': 0.9932469725608826}]

In [7]:
nlp_qusetion_answering = pipeline('question-answering')
nlp_qusetion_answering(context='Sure', question='Will I take A in Data Analysis?')

Some weights of the model checkpoint at distilbert-base-cased-distilled-squad were not used when initializing TFDistilBertForQuestionAnswering: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing TFDistilBertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TFDistilBertForQuestionAnswering were not initialized from the model checkpoint at distilbert-base-cased-distilled-squad and are newly initialized: ['dropout_39']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/kali/anaconda3/envs/teststackoverflow/lib/pyth

{'answer': 'Sure', 'end': 3, 'score': 0.6166552305221558, 'start': 0}

In [8]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_59']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [20]:
inputs = tokenizer([text_one, text_two])
inputs

{'input_ids': [[101, 2507, 2033, 1037, 3531, 102], [101, 2030, 2507, 2033, 1038, 3531, 1024, 1007, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [21]:
inputs_with_padding = tokenizer([text_one, text_two], padding = True, truncation = True, max_length = 256, return_tensors="tf")
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[ 101, 2507, 2033, 1037, 3531,  102,    0,    0,    0],
       [ 101, 2030, 2507, 2033, 1038, 3531, 1024, 1007,  102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [22]:
outputs = model(inputs_with_padding)
outputs

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-3.8784578,  4.1830215],
        [-2.4131548,  2.4914017]], dtype=float32)>,)

In [23]:
predictions = tf.nn.softmax(outputs[0], axis=-1)
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.1536023e-04, 9.9968469e-01],
       [7.3581878e-03, 9.9264187e-01]], dtype=float32)>

In [24]:
inputs = tokenizer([text_one, text_two, text_three])
inputs

{'input_ids': [[101, 2507, 2033, 1037, 3531, 102], [101, 2030, 2507, 2033, 1038, 3531, 1024, 1007, 102], [101, 1045, 2572, 15589, 5705, 6137, 15775, 2135, 2072, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [25]:
inputs_with_padding = tokenizer([text_one, text_two, text_three], padding = True, truncation = True, max_length = 256, return_tensors="tf")
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[  101,  2507,  2033,  1037,  3531,   102,     0,     0,     0,
            0],
       [  101,  2030,  2507,  2033,  1038,  3531,  1024,  1007,   102,
            0],
       [  101,  1045,  2572, 15589,  5705,  6137, 15775,  2135,  2072,
          102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [26]:
outputs = model(inputs_with_padding)
outputs

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-3.8784575,  4.1830215],
        [-2.413155 ,  2.491402 ],
        [-2.426911 ,  2.5640795]], dtype=float32)>,)

In [27]:
predictions = tf.nn.softmax(outputs[0], axis=-1)
predictions

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3.1536023e-04, 9.9968469e-01],
       [7.3581808e-03, 9.9264187e-01],
       [6.7530121e-03, 9.9324691e-01]], dtype=float32)>